version: '3.8'
services:
  redis:
    image: redis:6
    ports: ["6379:6379"]

  model-svc:
    build: ./model-svc
    ports: ["8001:8001"]
    depends_on:
      - redis
  
  backend:
    build: ./backend
    ports: ["8000:8000"]
    depends_on:
      - model-svc
      - redis
  
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    depends_on:
      - backend